name: arch-as-code ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11

    - uses: actions/setup-java@master
      with:
        java-version: 11

    - uses: actions/cache@master
      env:
        cache-name: cache-gradle
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build with Gradle
      run: ./gradlew build
      env: # Or as an environment variable
        STRUCTURIZR_API_KEY: ${{ secrets.TEST_STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.TEST_STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.TEST_STRUCTURIZR_WORKSPACE_ID }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: distributions
        path: build/distributions

    - name: Push Test Coverage
      run: ./scripts/push-to-code-coverage.sh
      env: # Or as an environment variable
        STRUCTURIZR_API_KEY: ${{ secrets.TEST_STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.TEST_STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.TEST_STRUCTURIZR_WORKSPACE_ID }}
        GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}

    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: ./gradlew run --args="publish ./documentation/products/arch-as-code"
      env:
        STRUCTURIZR_API_KEY: ${{ secrets.STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.PROD_STRUCTURIZR_WORKSPACE_ID }}
